# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from autohubcompany.models.base_model_ import Model
from autohubcompany import util


class CartBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: int=None, product_id: int=None, quantity: int=None):  # noqa: E501
        """CartBody - a model defined in Swagger

        :param user_id: The user_id of this CartBody.  # noqa: E501
        :type user_id: int
        :param product_id: The product_id of this CartBody.  # noqa: E501
        :type product_id: int
        :param quantity: The quantity of this CartBody.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'user_id': int,
            'product_id': int,
            'quantity': int
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'product_id': 'product_id',
            'quantity': 'quantity'
        }
        self._user_id = user_id
        self._product_id = product_id
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'CartBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cart_body of this CartBody.  # noqa: E501
        :rtype: CartBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> int:
        """Gets the user_id of this CartBody.


        :return: The user_id of this CartBody.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this CartBody.


        :param user_id: The user_id of this CartBody.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def product_id(self) -> int:
        """Gets the product_id of this CartBody.


        :return: The product_id of this CartBody.
        :rtype: int
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: int):
        """Sets the product_id of this CartBody.


        :param product_id: The product_id of this CartBody.
        :type product_id: int
        """

        self._product_id = product_id

    @property
    def quantity(self) -> int:
        """Gets the quantity of this CartBody.


        :return: The quantity of this CartBody.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this CartBody.


        :param quantity: The quantity of this CartBody.
        :type quantity: int
        """

        self._quantity = quantity
