# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from autohubcompany.models.base_model_ import Model
from autohubcompany import util


class OrderBodyUpdatedCart(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, cart_id: int=None, quantity: int=None):  # noqa: E501
        """OrderBodyUpdatedCart - a model defined in Swagger

        :param cart_id: The cart_id of this OrderBodyUpdatedCart.  # noqa: E501
        :type cart_id: int
        :param quantity: The quantity of this OrderBodyUpdatedCart.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'cart_id': int,
            'quantity': int
        }

        self.attribute_map = {
            'cart_id': 'cart_id',
            'quantity': 'quantity'
        }
        self._cart_id = cart_id
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'OrderBodyUpdatedCart':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The order_body_updated_cart of this OrderBodyUpdatedCart.  # noqa: E501
        :rtype: OrderBodyUpdatedCart
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cart_id(self) -> int:
        """Gets the cart_id of this OrderBodyUpdatedCart.

        The ID of the cart item.  # noqa: E501

        :return: The cart_id of this OrderBodyUpdatedCart.
        :rtype: int
        """
        return self._cart_id

    @cart_id.setter
    def cart_id(self, cart_id: int):
        """Sets the cart_id of this OrderBodyUpdatedCart.

        The ID of the cart item.  # noqa: E501

        :param cart_id: The cart_id of this OrderBodyUpdatedCart.
        :type cart_id: int
        """

        self._cart_id = cart_id

    @property
    def quantity(self) -> int:
        """Gets the quantity of this OrderBodyUpdatedCart.

        The quantity for the cart item.  # noqa: E501

        :return: The quantity of this OrderBodyUpdatedCart.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this OrderBodyUpdatedCart.

        The quantity for the cart item.  # noqa: E501

        :param quantity: The quantity of this OrderBodyUpdatedCart.
        :type quantity: int
        """

        self._quantity = quantity
