# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from autohubcompany.models.base_model_ import Model
from autohubcompany.models.order_body_updated_cart import OrderBodyUpdatedCart  # noqa: F401,E501
from autohubcompany import util


class OrderBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, delivery_date: datetime=None, user_id: int=None, updated_cart: List[OrderBodyUpdatedCart]=None):  # noqa: E501
        """OrderBody - a model defined in Swagger

        :param delivery_date: The delivery_date of this OrderBody.  # noqa: E501
        :type delivery_date: datetime
        :param user_id: The user_id of this OrderBody.  # noqa: E501
        :type user_id: int
        :param updated_cart: The updated_cart of this OrderBody.  # noqa: E501
        :type updated_cart: List[OrderBodyUpdatedCart]
        """
        self.swagger_types = {
            'delivery_date': datetime,
            'user_id': int,
            'updated_cart': List[OrderBodyUpdatedCart]
        }

        self.attribute_map = {
            'delivery_date': 'delivery_date',
            'user_id': 'user_id',
            'updated_cart': 'updated_cart'
        }
        self._delivery_date = delivery_date
        self._user_id = user_id
        self._updated_cart = updated_cart

    @classmethod
    def from_dict(cls, dikt) -> 'OrderBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The order_body of this OrderBody.  # noqa: E501
        :rtype: OrderBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def delivery_date(self) -> datetime:
        """Gets the delivery_date of this OrderBody.


        :return: The delivery_date of this OrderBody.
        :rtype: datetime
        """
        return self._delivery_date

    @delivery_date.setter
    def delivery_date(self, delivery_date: datetime):
        """Sets the delivery_date of this OrderBody.


        :param delivery_date: The delivery_date of this OrderBody.
        :type delivery_date: datetime
        """

        self._delivery_date = delivery_date

    @property
    def user_id(self) -> int:
        """Gets the user_id of this OrderBody.


        :return: The user_id of this OrderBody.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this OrderBody.


        :param user_id: The user_id of this OrderBody.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def updated_cart(self) -> List[OrderBodyUpdatedCart]:
        """Gets the updated_cart of this OrderBody.


        :return: The updated_cart of this OrderBody.
        :rtype: List[OrderBodyUpdatedCart]
        """
        return self._updated_cart

    @updated_cart.setter
    def updated_cart(self, updated_cart: List[OrderBodyUpdatedCart]):
        """Sets the updated_cart of this OrderBody.


        :param updated_cart: The updated_cart of this OrderBody.
        :type updated_cart: List[OrderBodyUpdatedCart]
        """

        self._updated_cart = updated_cart
