# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from autohubcompany.models.base_model_ import Model
from autohubcompany.models.order_body_updated_cart import OrderBodyUpdatedCart  # noqa: F401,E501
from autohubcompany import util


class UpdateCart(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """UpdateCart - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateCart':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The update_cart of this UpdateCart.  # noqa: E501
        :rtype: UpdateCart
        """
        return util.deserialize_model(dikt, cls)
